// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKtW53AiumrDh9LSpcRmmXGTmZS8YeW8Q',
    appId: '1:164666468336:web:21e3e32d1c4930ff9f5f35',
    messagingSenderId: '164666468336',
    projectId: 'sisinfo-adadb',
    authDomain: 'sisinfo-adadb.firebaseapp.com',
    databaseURL: 'https://sisinfo-adadb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisinfo-adadb.firebasestorage.app',
    measurementId: 'G-JBEPEPGGQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxDlErffe52_nZw96i0P8oEv_qtgw3QY',
    appId: '1:164666468336:android:83aee28c3331660a9f5f35',
    messagingSenderId: '164666468336',
    projectId: 'sisinfo-adadb',
    databaseURL: 'https://sisinfo-adadb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisinfo-adadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJ-jDFTWqc3iDmGMdFXw6X2r4EaPscoM',
    appId: '1:164666468336:ios:ad44b2b3694730589f5f35',
    messagingSenderId: '164666468336',
    projectId: 'sisinfo-adadb',
    databaseURL: 'https://sisinfo-adadb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisinfo-adadb.firebasestorage.app',
    iosBundleId: 'com.example.sisinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKJ-jDFTWqc3iDmGMdFXw6X2r4EaPscoM',
    appId: '1:164666468336:ios:ad44b2b3694730589f5f35',
    messagingSenderId: '164666468336',
    projectId: 'sisinfo-adadb',
    databaseURL: 'https://sisinfo-adadb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisinfo-adadb.firebasestorage.app',
    iosBundleId: 'com.example.sisinfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKtW53AiumrDh9LSpcRmmXGTmZS8YeW8Q',
    appId: '1:164666468336:web:9c3ca3d7c98bf7a69f5f35',
    messagingSenderId: '164666468336',
    projectId: 'sisinfo-adadb',
    authDomain: 'sisinfo-adadb.firebaseapp.com',
    databaseURL: 'https://sisinfo-adadb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sisinfo-adadb.firebasestorage.app',
    measurementId: 'G-XY4STTFHXY',
  );

}